name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*'  # Esto se ejecuta para cualquier tag que empiece con "v"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: imprime variable
      run: echo "variable: ${{ secrets.DOCKER_USERNAME }}"
      
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .  # Carpeta donde está el Dockerfile, normalmente el root del repo
        dockerfile: ./Dockerfile  # Ruta relativa al Dockerfile
        push: true
        tags: carlose380/your_image_name:${{ github.ref_name }}  # Usar el tag como versión de la imagen
